# Generated by Django 5.1.4 on 2025-04-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile_billing_address_profile_card_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='article',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='printer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='printer',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Формат: ШхГхВ (мм)', max_length=50, verbose_name='Габариты'),
        ),
        migrations.AddField(
            model_name='printer',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='printer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
